const productsTypes = {
   ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
   FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
   SET_PRODUCTS: "SET_PRODUCTS",
   DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
   FETCH_PRODUCT: 'FETCH_PRODUCT',
   SET_PROD: 'SET_PROD'
};

export default productsTypes;
